// apps/web-vue/components/MessageBubble.vue
<script setup lang="ts">
import { renderMarkdown } from "@agentos/ui/markdown";

import type { ChatMessage } from "~/types";

const props = defineProps<{ message: ChatMessage }>();
const isUser = computed(() => props.message.role === "user");
const html = ref("");

watch(
  [() => props.message.content, isUser],
  async ([content, asUser]) => {
    if (asUser || !content) {
      html.value = "";
      return;
    }
    html.value = await renderMarkdown(content as string);
  },
  { immediate: true },
);
</script>

<template>
  <div :class="['flex', isUser ? 'justify-end' : 'justify-start']">
    <div
      :class="[
        'max-w-[85%] rounded-xl px-4 py-2.5 text-sm leading-relaxed',
        isUser
          ? 'bg-accent-blue text-white'
          : 'assistant-bubble border border-bg-elevated bg-bg-card text-text-primary',
      ]"
    >
      <div v-if="message.attachments?.length" class="mb-2 flex flex-wrap gap-1">
        <span
          v-for="att in message.attachments"
          :key="att.filename"
          class="rounded-md bg-bg-elevated px-2 py-0.5 font-mono text-[10px] text-text-secondary"
        >
          {{ att.filename }}
        </span>
      </div>

      <template v-if="isUser">
        <p v-if="message.content" class="whitespace-pre-wrap">{{ message.content }}</p>
      </template>
      <template v-else-if="message.content">
        <div v-if="html" v-html="html" />
        <p v-else class="whitespace-pre-wrap">{{ message.content }}</p>
        <SourcePills :web="message.webSources" :rag="message.ragSources" />
      </template>
      <span v-else class="inline-flex items-center gap-1 text-text-muted">
        <span class="thinking-dot inline-block h-1.5 w-1.5 rounded-full bg-text-muted" />
        <span class="thinking-dot inline-block h-1.5 w-1.5 rounded-full bg-text-muted" />
        <span class="thinking-dot inline-block h-1.5 w-1.5 rounded-full bg-text-muted" />
      </span>
    </div>
  </div>
</template>

// apps/web-next/src/components/MessageBubble.tsx
"use client";

import { useEffect, useState } from "react";

import type { ChatMessage } from "@/lib/types";

import { SourcePills } from "./SourcePills";

export function MessageBubble({ message }: { message: ChatMessage }) {
  const isUser = message.role === "user";
  const [html, setHtml] = useState("");

  useEffect(() => {
    if (isUser || !message.content) {
      setHtml("");
      return;
    }
    let cancelled = false;
    import("@agentos/ui/markdown").then(({ renderMarkdown }) => {
      renderMarkdown(message.content).then((rendered) => {
        if (!cancelled) setHtml(rendered);
      });
    });
    return () => {
      cancelled = true;
    };
  }, [isUser, message.content]);

  return (
    <div className={`flex ${isUser ? "justify-end" : "justify-start"}`}>
      <div
        className={`max-w-[85%] rounded-xl px-4 py-2.5 text-sm leading-relaxed ${
          isUser
            ? "bg-accent-blue text-white"
            : "assistant-bubble border border-bg-elevated bg-bg-card text-text-primary"
        }`}
      >
        {message.attachments?.length ? (
          <div className="mb-2 flex flex-wrap gap-1">
            {message.attachments.map((att) => (
              <span
                key={att.filename}
                className="rounded-md bg-bg-elevated px-2 py-0.5 font-mono text-[10px] text-text-secondary"
              >
                {att.filename}
              </span>
            ))}
          </div>
        ) : null}

        {isUser ? (
          message.content ? (
            <p className="whitespace-pre-wrap">{message.content}</p>
          ) : null
        ) : message.content ? (
          <>
            {html ? (
              <div dangerouslySetInnerHTML={{ __html: html }} />
            ) : (
              <p className="whitespace-pre-wrap">{message.content}</p>
            )}
            <SourcePills web={message.webSources} rag={message.ragSources} />
          </>
        ) : (
          <span className="inline-flex items-center gap-1 text-text-muted">
            <span className="thinking-dot inline-block h-1.5 w-1.5 rounded-full bg-text-muted" />
            <span className="thinking-dot inline-block h-1.5 w-1.5 rounded-full bg-text-muted" />
            <span className="thinking-dot inline-block h-1.5 w-1.5 rounded-full bg-text-muted" />
          </span>
        )}
      </div>
    </div>
  );
}
